version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "724:724"
      - "3827:3827"

networks:
  default:
    external: true
    name: network8
